roll_pitch_yawrate_thrust_controller:
  ros__parameters:
    mass: 0.52
    inertia:
      xx: 0.0347563
      xy: 0.0
      xz: 0.0
      yy: 0.0458929
      yz: 0.0
      zz: 0.0977

    rotor_configuration:
      0:
        angle: -0.78539
        arm_length: 0.09
        rotor_force_constant: 8.54858e-06
        rotor_moment_constant: 1.6e-2
        direction: 1.0
      1:
        angle: 2.35619
        arm_length: 0.09
        rotor_force_constant: 8.54858e-06
        rotor_moment_constant: 1.6e-2
        direction: 1.0
      2:
        angle: 0.78539
        arm_length: 0.09
        rotor_force_constant: 8.54858e-06
        rotor_moment_constant: 1.6e-2
        direction: -1.0
      3:
        angle: -2.35619
        arm_length: 0.09
        rotor_force_constant: 8.54858e-06
        rotor_moment_constant: 1.6e-2
        direction: -1.0
